export default {

    INPUT_SEARCH_CHANGE_VALUE: 'INPUT_SEARCH_CHANGE_VALUE',
    SET_PRODUCTS_IN_TABLE : 'SET_PRODUCTS_IN_TABLE',
    SET_PRODUCTS_IN_FAST_RESULT_CONTAINER : 'SET_PRODUCTS_IN_FAST_RESULT_CONTAINER',
    SET_VALUE_IN_INPUT_FAST_SEARCH : 'SET_VALUE_IN_INPUT_FAST_SEARCH',
    HIDDEN_FAST_SEARCH_RESULT : 'HIDDEN_FAST_SEARCH_RESULT',
    SHOW_FAST_SEARCH_RESULT : 'SHOW_FAST_SEARCH_RESULT',


    LOAD_IMPORTERS : 'LOAD_IMPORTERS',
    SET_BRAND : 'SET_BRAND',


    // InputProduct
    INPUT_PRODUCT_CHANGE_TYPE_SEARCH: 'INPUT_PRODUCT_CHANGE_TYPE_SEARCH',
    INPUT_PRODUCT_SET_RESULT : 'INPUT_PRODUCT_SET_RESULT',
    INPUT_PRODUCT_HIDDEN_RESULT : 'INPUT_PRODUCT_HIDDEN_RESULT',
    INPUT_PRODUCT_SHOW_RESULT : 'INPUT_PRODUCT_SHOW_RESULT',
    INPUT_PRODUCT_SET_VALUE : 'INPUT_PRODUCT_SET_VALUE',

    //InputBrand
    INPUT_BRAND_SET_RESULT : 'INPUT_BRAND_SET_RESULT',
    INPUT_BRAND_HIDDEN_RESULT : 'INPUT_BRAND_HIDDEN_RESULT',
    INPUT_BRAND_SHOW_RESULT : 'INPUT_BRAND_SHOW_RESULT',
    INPUT_BRAND_SET_VALUE : 'INPUT_BRAND_SET_VALUE',

    //InputArticle
    INPUT_ARTICLE_SET_RESULT : 'INPUT_ARTICLE_SET_RESULT',
    INPUT_ARTICLE_HIDDEN_RESULT : 'INPUT_ARTICLE_HIDDEN_RESULT',
    INPUT_ARTICLE_SHOW_RESULT : 'INPUT_ARTICLE_SHOW_RESULT',
    INPUT_ARTICLE_SET_VALUE : 'INPUT_ARTICLE_SET_VALUE',

    //InputOe
    INPUT_OE_SHOW_RESULT : 'INPUT_OE_SHOW_RESULT',
    INPUT_OE_HIDDEN_RESULT : 'INPUT_OE_HIDDEN_RESULT',
    INPUT_OE_SET_RESULT : 'INPUT_OE_SET_RESULT',
    INPUT_OE_SET_VALUE : 'INPUT_OE_SET_VALUE',

    //InputProductType
    INPUT_PRODUCT_TYPE_SHOW_RESULT : 'INPUT_PRODUCT_TYPE_SHOW_RESULT',
    INPUT_PRODUCT_TYPE_HIDDEN_RESULT : 'INPUT_PRODUCT_TYPE_HIDDEN_RESULT',
    INPUT_PRODUCT_TYPE_SET_RESULT : 'INPUT_PRODUCT_TYPE_SET_RESULT',
    INPUT_PRODUCT_TYPE_SET_VALUE : 'INPUT_PRODUCT_TYPE_SET_VALUE',

    //InputMANUFACTURE
    INPUT_MANUFACTURE_SHOW_RESULT : 'INPUT_MANUFACTURE_SHOW_RESULT',
    INPUT_MANUFACTURE_HIDDEN_RESULT : 'INPUT_MANUFACTURE_HIDDEN_RESULT',
    INPUT_MANUFACTURE_SET_RESULT : 'INPUT_MANUFACTURE_SET_RESULT',
    INPUT_MANUFACTURE_SET_VALUE : 'INPUT_MANUFACTURE_SET_VALUE',

    //InputProductAttributeType
    INPUT_PRODUCT_ATTRIBUTE_TYPE_SHOW_RESULT : 'INPUT_PRODUCT_ATTRIBUTE_TYPE_SHOW_RESULT',
    INPUT_PRODUCT_ATTRIBUTE_TYPE_HIDDEN_RESULT : 'INPUT_PRODUCT_ATTRIBUTE_TYPE_HIDDEN_RESULT',
    INPUT_PRODUCT_ATTRIBUTE_TYPE_SET_RESULT : 'INPUT_PRODUCT_ATTRIBUTE_TYPE_SET_RESULT',
    INPUT_PRODUCT_ATTRIBUTE_TYPE_SET_VALUE : 'INPUT_PRODUCT_ATTRIBUTE_TYPE_SET_VALUE',

    //ProductEdit
    PRODUCT_LOAD_ATTR : 'PRODUCT_LOAD_ATTR',
    PRODUCT_SET_OE : 'PRODUCT_SET_OE',
    PRODUCT_SET_PRODUCT : 'PRODUCT_SET_PRODUCT',
    PRODUCT_SET_ARTICLE : 'PRODUCT_SET_ARTICLE',
    PRODUCT_SET_BRAND : 'PRODUCT_SET_BRAND',
    PRODUCT_SET_TYPE : 'PRODUCT_SET_TYPE',
    PRODUCT_SET_IMPORTER : 'PRODUCT_SET_IMPORTER',
    PRODUCT_SET_PRICE : 'PRODUCT_SET_PRICE',
    PRODUCT_SET_PLACE : 'PRODUCT_SET_PLACE',
    PRODUCT_SET_DESCRIPTION : 'PRODUCT_SET_DESCRIPTION',
    PRODUCT_SET_COUNT : 'PRODUCT_SET_COUNT',
    PRODUCT_SET_DATE : 'PRODUCT_SET_DATE',
    PRODUCT_ADD_OE : 'PRODUCT_ADD_OE',
    PRODUCT_DELETE_OE : 'PRODUCT_DELETE_OE',

    SET_CURRENT_PRODUCT_ATTR : 'SET_CURRENT_PRODUCT_ATTR',
    SET_CURRENT_PRODUCT_ATTR_NAME : 'SET_CURRENT_PRODUCT_ATTR_NAME',

    MODAL_BRAND_ADD_SHOW : 'MODAL_BRAND_ADD_SHOW',
    MODAL_PRODUCT_HIDDEN : 'MODAL_PRODUCT_HIDDEN',
    MODAL_PRODUCT_TYPE_ADD_SHOW : 'MODAL_PRODUCT_TYPE_ADD_SHOW',
    MODAL_PRODUCT_ADD_CROSS_BY_PRODUCT_ID_SHOW : 'MODAL_PRODUCT_ADD_CROSS_BY_PRODUCT_ID_SHOW',
    MODAL_PRODUCT_ADD_ATTRIBUTE_SHOW : 'MODAL_PRODUCT_ADD_ATTRIBUTE_SHOW',
    MODAL_PRODUCT_ADD_OE_SHOW : 'MODAL_PRODUCT_ADD_OE_SHOW',
    MODAL_PRODUCT_COPY_OE_SHOW : 'MODAL_PRODUCT_COPY_OE_SHOW',
    MODAL_PRODUCT_COPY_SHOW : 'MODAL_PRODUCT_COPY_SHOW',
    MODAL_ADD_ATTRIBUTE_SHOW : 'MODAL_ADD_ATTRIBUTE_SHOW',
    MODAL_ADD_OE_SHOW : 'MODAL_ADD_OE_SHOW',
    MODAL_ATTRIBUTE_EDIT_NAME_SHOW : 'MODAL_ATTRIBUTE_EDIT_NAME_SHOW',


};
